export const HISTORY_DAYS = 180;
export const CHARACTER_COUNT = 365;

export const POOLS = {
    R: {
        firstSeq: 1,
        lastSeq: 900,
        users: 900,
    },
    A: {
        firstSeq: 901,
        lastSeq: 7900,
        users: 7000,
    },
    B: {
        firstSeq: 7901,
        lastSeq: 8100,
        users: 200,
    },
};

export const TOTAL_USERS =
    POOLS.R.users +
    POOLS.A.users +
    POOLS.B.users;

export const HISTORICAL_SESSIONS =
    TOTAL_USERS * HISTORY_DAYS;

export const TODAY_SESSIONS = POOLS.B.users;

export const SYNTHETIC_STORY = [
    "A learner meets a character at the entrance to a quiet library.",
    "They imagine a simple scene, connect its sound to the picture, and remember its meaning.",
    "After one practice question, they return the next day and repeat the same learning routine.",
    "This text is synthetic, shared by all staging characters, and never generated by an AI provider.",
].join(" ");

export const SYNTHETIC_STORY_SOURCE = "perf-synthetic";

export const PERF_PASSWORD_HASH_ROUNDS = 10;